modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Silkier%20Touch"
iconFile="icon.png"

[[mods]]
modId="silkiertouch"
version="1.4"
displayName="Silkier Touch"
displayURL="https://serilum.com/mod/silkier-touch"
authors="Serilum"
description='''Extends Silk Touch functionality! Dragon eggs, spawners, cake, farmland and more!
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.silkiertouch]]
    modId="collective"
    type="required"
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.silkiertouch]]
    modId="minecraft"
    type="required"
    versionRange="[26.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "silkiertouch.mixins.json"